# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  # Windows 7 90 day trial
  config.vm.box = "modernIE/w7-ie11"
  config.vm.hostname = "USMMC"
  config.vm.provider :virtualbox do |vb|
    vb.name = "USMMC"
  end  

  config.vm.provider "virtualbox" do |vb|
     # Display the VirtualBox GUI when booting the machine
     vb.gui = true
     # Customize the amount of memory on the VM:
     vb.memory = "2048"
     #Disable USB
     vb.customize ["modifyvm", :id, "--usb", "off"]
     vb.customize ["modifyvm", :id, "--usbehci", "off"]
  end
  
  # run the installation scripts
  config.vm.provision :shell, path: "scripts/install-dot-net.ps1"
  config.vm.provision :shell, path: "scripts/Install-USMMC.ps1"
  
end
